version: '3'

services:
  # Database service
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: pokemon_go
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/postgresql/data

  # Node.js app service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      PORT: 8080
      DB_USERNAME: admin
      DB_PASSWORD: admin
      DB_NAME: pokemon_go
      DB_HOST: db  # Update to use the service name of the database container
      DB_DIALECT: postgres
      XLSX_FILE_PATH: /usr/src/app/desktop/Pokemon Go.xlsx  # Adjust the path inside the container
    ports:
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      - db
    volumes:
    - /Users/test/Desktop:/usr/src/app/desktop
    command: bash -c "npm install && npx wait-for-it db:5432 -t 60 -- npm run db:all && npm run start"


networks:
  app_network:
    driver: bridge

volumes:
  db_data:
